"""
This script stores data about county and municipality codes.
The code to get the data is showed in comments.
"""

# muni = pd.read_csv("data/municipios.csv")
# muni
# provincia_id	provincia	municipio_id	municipio
# 0	48	Bizkaia	1	Abadiño
# 1	20	Gipuzkoa	1	Abaltzisketa
# 2	48	Bizkaia	2	Abanto y Ciérvana-Abanto Zierbena
# 3	20	Gipuzkoa	2	Aduna
# 4	1	Araba/Álava	51	Agurain/Salvatierra
# ...	...	...	...	...
# 247	48	Bizkaia	915	Ziortza-Bolibar
# 248	20	Gipuzkoa	28	Zizurkil
# 249	1	Araba/Álava	63	Zuia
# 250	20	Gipuzkoa	81	Zumaia
# 251	20	Gipuzkoa	80	Zumarraga

# provincias = muni.loc[:, ["provincia_id", "provincia"]].set_index("provincia")["provincia_id"].to_dict()
provincias = {'Bizkaia': 48, 'Gipuzkoa': 20, 'Araba/Álava': 1}

# provincias_ = {v: k for k, v in provincias.items()}
provincias_ = {48: 'Bizkaia', 20: 'Gipuzkoa', 1: 'Araba/Álava'}

# municipios = {}
# for provincia, provincia_id in provincias.items():
#     municipios[provincia] = muni.loc[muni["provincia_id"] == provincia_id, ["municipio_id", "municipio"]].set_index("municipio")["municipio_id"].to_dict()
municipios = {'Bizkaia': {'Abadiño': 1,
                          'Abanto y Ciérvana-Abanto Zierbena': 2,
                          'Ajangiz': 911,
                          'Alonsotegi': 912,
                          'Amorebieta-Etxano': 3,
                          'Amoroto': 4,
                          'Arakaldo': 5,
                          'Arantzazu': 6,
                          'Areatza': 93,
                          'Arrankudiaga-Zollo': 9,
                          'Arratzu': 914,
                          'Arrieta': 10,
                          'Arrigorriaga': 11,
                          'Artea': 23,
                          'Artzentales': 8,
                          'Atxondo': 91,
                          'Aulesti': 70,
                          'Bakio': 12,
                          'Balmaseda': 90,
                          'Barakaldo': 13,
                          'Barrika': 14,
                          'Basauri': 15,
                          'Bedia': 92,
                          'Berango': 16,
                          'Bermeo': 17,
                          'Berriatua': 18,
                          'Berriz': 19,
                          'Bilbao': 20,
                          'Busturia': 21,
                          'Derio': 901,
                          'Dima': 26,
                          'Durango': 27,
                          'Ea': 28,
                          'Elantxobe': 31,
                          'Elorrio': 32,
                          'Erandio': 902,
                          'Ereño': 33,
                          'Ermua': 34,
                          'Errigoiti': 79,
                          'Etxebarri': 29,
                          'Etxebarria': 30,
                          'Forua': 906,
                          'Fruiz': 35,
                          'Galdakao': 36,
                          'Galdames': 37,
                          'Gamiz-Fika': 38,
                          'Garai': 39,
                          'Gatika': 40,
                          'Gautegiz Arteaga': 41,
                          'Gernika-Lumo': 46,
                          'Getxo': 44,
                          'Gizaburuaga': 47,
                          'Gordexola': 42,
                          'Gorliz': 43,
                          'Güeñes': 45,
                          'Ibarrangelu': 48,
                          'Igorre': 94,
                          'Ispaster': 49,
                          'Iurreta': 910,
                          'Izurtza': 50,
                          'Karrantza Harana/Valle de Carranza': 22,
                          'Kortezubi': 907,
                          'Lanestosa': 51,
                          'Larrabetzu': 52,
                          'Laukiz': 53,
                          'Leioa': 54,
                          'Lekeitio': 57,
                          'Lemoa': 55,
                          'Lemoiz': 56,
                          'Lezama': 81,
                          'Loiu': 903,
                          'Mallabia': 58,
                          'Mañaria': 59,
                          'Markina-Xemein': 60,
                          'Maruri-Jatabe': 61,
                          'Mendata': 62,
                          'Mendexa': 63,
                          'Meñaka': 64,
                          'Morga': 66,
                          'Mundaka': 68,
                          'Mungia': 69,
                          'Munitibar-Arbatzegi Gerrikaitz': 7,
                          'Murueta': 908,
                          'Muskiz': 71,
                          'Muxika': 67,
                          'Nabarniz': 909,
                          'Ondarroa': 73,
                          'Orozko': 75,
                          'Ortuella': 83,
                          'Otxandio': 72,
                          'Plentzia': 77,
                          'Portugalete': 78,
                          'Santurtzi': 82,
                          'Sestao': 84,
                          'Sondika': 904,
                          'Sopela': 85,
                          'Sopuerta': 86,
                          'Sukarrieta': 76,
                          'Trucios-Turtzioz': 87,
                          'Ubide': 88,
                          'Ugao-Miraballes': 65,
                          'Urduliz': 89,
                          'Urduña/Orduña': 74,
                          'Usansolo': 916,
                          'Valle de Trápaga-Trapagaran': 80,
                          'Zaldibar': 95,
                          'Zalla': 96,
                          'Zamudio': 905,
                          'Zaratamo': 97,
                          'Zeanuri': 24,
                          'Zeberio': 25,
                          'Zierbena': 913,
                          'Ziortza-Bolibar': 915},
              'Gipuzkoa': {'Abaltzisketa': 1,
                           'Aduna': 2,
                           'Aia': 16,
                           'Aizarnazabal': 3,
                           'Albiztur': 4,
                           'Alegia': 5,
                           'Alkiza': 6,
                           'Altzaga': 906,
                           'Altzo': 7,
                           'Amezketa': 8,
                           'Andoain': 9,
                           'Anoeta': 10,
                           'Antzuola': 11,
                           'Arama': 12,
                           'Aretxabaleta': 13,
                           'Arrasate/Mondragón': 55,
                           'Asteasu': 14,
                           'Astigarraga': 903,
                           'Ataun': 15,
                           'Azkoitia': 17,
                           'Azpeitia': 18,
                           'Baliarrain': 904,
                           'Beasain': 19,
                           'Beizama': 20,
                           'Belauntza': 21,
                           'Berastegi': 22,
                           'Bergara': 74,
                           'Berrobi': 23,
                           'Bidania-Goiatz': 24,
                           'Deba': 29,
                           'Donostia / San Sebastián': 69,
                           'Eibar': 30,
                           'Elduain': 31,
                           'Elgeta': 33,
                           'Elgoibar': 32,
                           'Errenteria': 67,
                           'Errezil': 66,
                           'Eskoriatza': 34,
                           'Ezkio-Itsaso': 35,
                           'Gabiria': 38,
                           'Gaintza': 37,
                           'Gaztelu': 907,
                           'Getaria': 39,
                           'Hernani': 40,
                           'Hernialde': 41,
                           'Hondarribia': 36,
                           'Ibarra': 42,
                           'Idiazabal': 43,
                           'Ikaztegieta': 44,
                           'Irun': 45,
                           'Irura': 46,
                           'Itsasondo': 47,
                           'Larraul': 48,
                           'Lasarte-Oria': 902,
                           'Lazkao': 49,
                           'Leaburu': 50,
                           'Legazpi': 51,
                           'Legorreta': 52,
                           'Leintz-Gatzaga': 68,
                           'Lezo': 53,
                           'Lizartza': 54,
                           'Mendaro': 901,
                           'Mutiloa': 57,
                           'Mutriku': 56,
                           'Oiartzun': 63,
                           'Olaberria': 58,
                           'Oñati': 59,
                           'Ordizia': 76,
                           'Orendain': 905,
                           'Orexa': 60,
                           'Orio': 61,
                           'Ormaiztegi': 62,
                           'Pasaia': 64,
                           'Segura': 70,
                           'Soraluze-Placencia de las Armas': 65,
                           'Tolosa': 71,
                           'Urnieta': 72,
                           'Urretxu': 77,
                           'Usurbil': 73,
                           'Villabona': 75,
                           'Zaldibia': 78,
                           'Zarautz': 79,
                           'Zegama': 25,
                           'Zerain': 26,
                           'Zestoa': 27,
                           'Zizurkil': 28,
                           'Zumaia': 81,
                           'Zumarraga': 80},
              'Araba/Álava': {'Agurain/Salvatierra': 51,
                              'Alegría-Dulantzi': 1,
                              'Amurrio': 2,
                              'Añana': 49,
                              'Aramaio': 3,
                              'Armiñón': 6,
                              'Arraia-Maeztu': 37,
                              'Arratzua-Ubarrundia': 8,
                              'Artziniega': 4,
                              'Asparrena': 9,
                              'Ayala/Aiara': 10,
                              'Baños de Ebro/Mañueta': 11,
                              'Barrundia': 13,
                              'Berantevilla': 14,
                              'Bernedo': 16,
                              'Campezo/Kanpezu': 17,
                              'Elburgo/Burgelu': 21,
                              'Elciego': 22,
                              'Elvillar/Bilar': 23,
                              'Erriberagoitia/Ribera Alta': 46,
                              'Harana/Valle de Arana': 56,
                              'Iruña Oka/Iruña de Oca': 901,
                              'Iruraiz-Gauna': 27,
                              'Kripan': 19,
                              'Kuartango': 20,
                              'Labastida/Bastida': 28,
                              'Lagrán': 30,
                              'Laguardia': 31,
                              'Lanciego/Lantziego': 32,
                              'Lantarón': 902,
                              'Lapuebla de Labarca': 33,
                              'Laudio/Llodio': 36,
                              'Legutio': 58,
                              'Leza': 34,
                              'Moreda de Álava/Moreda Araba': 39,
                              'Navaridas': 41,
                              'Okondo': 42,
                              'Oyón-Oion': 43,
                              'Peñacerrada-Urizaharra': 44,
                              'Ribera Baja/Erriberabeitia': 47,
                              'Samaniego': 52,
                              'San Millán/Donemiliaga': 53,
                              'Urkabustaiz': 54,
                              'Valdegovía/Gaubea': 55,
                              'Villabuena de Álava/Eskuernaga': 57,
                              'Vitoria-Gasteiz': 59,
                              'Yécora/Iekora': 60,
                              'Zalduondo': 61,
                              'Zambrana': 62,
                              'Zigoitia': 18,
                              'Zuia': 63}}